### ISSUE TITLE
Development workflow doesn't work for me

### ISSUE THREAD

**Issue by jd41** [telamonian/tree-finder#56]
When I try to follow the development instructions in README.md and `yarn start` the `simple` example, I get the error

"Error: Can't resolve '~tree-finder/dist/tree-finder.css' in '/home/ubuntu/tree-finder/examples/simple/style' ".

**Comment by telamonian** [comment]
yeah, there's currently a dependency issue where you have to build all three packages in the project in a certain sequence. I'll try to resolve that.

In the meantime, you should be able to get everything builT by first running

```
yarn webpack
```

in the top level of this repo. That uses lerna to resolve the interdependency. After that command succeeds, you should be able to run `yarn start` in the `examples/simple` dir to start the dev server.

Please let me know if that resolves the issue

**Comment by jd41** [comment]
Yes, that works, thank you!

**Comment by telamonian** [comment]
Great! Feel free to open a new issue if you run into any more trouble
